### ISSUE TITLE
バトル結果がちゃんと見える画面があるといい

### ISSUE THREAD

**Issue by hashi0203** [team-tissis/polylemma-client#163]

**Comment by katoatsushi** [comment]
![Screen Shot 2023-02-28 at 11 58 09](https://user-images.githubusercontent.com/42636663/221742260-4305ba3b-ab44-4e7e-9f82-dd29014335d4.png)
![Screen Shot 2023-02-28 at 12 00 18](https://user-images.githubusercontent.com/42636663/221742426-dddfd08a-d1f4-4aa5-8541-42a1319ba08f.png)

**Comment by katoatsushi** [comment]
このイシューに対するプルリクマージしてしまった ↓
https://github.com/team-tissis/polylemma-client/pull/165

**Comment by hashi0203** [comment]
それが見やすくなるのも嬉しい！

説明不十分やったんやけど、本来のイメージはバトル結果が一覧できる画面的なもの←1
まぁでもこれはマルチバトルができるようになって、バトルの ID が設定されるようになってからの方がいいかも

あとは、現状ではバトルが終了した状態でリロードするとメインの画面に戻っちゃうからバトル結果わからずに終了してしまう状態で、メインに戻るんじゃなくてバトル結果画面があるといいかなぁっていうのもある←2

1と2はおんなじ画面でも違う画面でもいい気がする

**Comment by katoatsushi** [comment]
承知！

**Comment by katoatsushi** [comment]
@hashi0203 
修正したものをdevelopブランチにマージしといた
