### ISSUE TITLE
ガチャ引いてもリロードするまでコインの数変更されない

### ISSUE THREAD

**Issue by hashi0203** [team-tissis/polylemma-client#37]

**Comment by katoatsushi** [comment]
これはreduxで値を管理させないといけない部分だと思う

**Comment by hashi0203** [comment]
ガチャを引く操作は Gacha.jsx の画面でするけど、header.jsx に書いてあるコインの枚数変更させるには redux が必要っていうこと？
同じファイルで書いてない場合、同じ画面に映ってるものであっても、データを共有するためには redux が必要っていう認識で OK?

**Comment by hashi0203** [comment]
`Index.jsx` でコインの数とかの更新変数と更新処理をグルーバルに設定して、各画面に引数で渡せばいいんかな？

**Comment by hashi0203** [comment]
#126 で対応
